if has('packages')
  packadd! airline
  packadd! airline-themes
  packadd! ale
  packadd! arduino
  packadd! completor
  packadd! fugitive
  packadd! go
  packadd! helm
  packadd! indentline
  packadd! markdown
  packadd! nerdcommenter
  packadd! nerdtree
  packadd! repeat
  packadd! rhubarb
  packadd! snippets
  packadd! surround
  packadd! toml
  packadd! ultisnips
  packadd! unimpaired
  packadd! vifm
endif

if has('unnamedplus')
  set clipboard=unnamed,unnamedplus
endif
