[General]
  snippetdirs = ["/home/jhe/Git/github.com/helmecke/pet-snippets/", "/home/jhe/Git/github.com/t3n/pet-snippets/"]
  editor = "nvim"
  column = 40
  selectcmd = "fzf --ansi -m"
  sortby = ""
